# fly.toml app configuration file generated for demo-chat-bot-fe-autumn-breeze-6009 on 2024-10-07T17:15:44+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'demo-chat-bot-fe-autumn-breeze-6009'
primary_region = 'hkg'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
