export enum ERROR_CODE {
  // ERROR MESSAGE CODE
  UNKNOWN = '#UNKNOWN',
  ID_NOT_VALID = '#ID_NOT_VALID',
  FILTER_NOT_EMPTY = '#FILTER_NOT_EMPTY',
  EMPTY = '#IS_EMPTY',
  NO_DATA_MATCH = '#NO_DATA_MATCH',
  NO_DATA_CHANGE = '#NO_DATA_CHANGE',

  // ERROR TYPE CODE
  NOT_VALID = '#NOT_VALID',
  TRY_CATCH = '#TRY_CATCH',
  BAD_GATEWAY = '#BAD_GATEWAY',
  BAD_REQUEST = '#BAD_REQUEST',
  BASE_CREATE_ERROR = '#BASE_CREATE_ERROR',
  BASE_CREATE_ARRAY_ERROR = '#BASE_CREATE_ARRAY_ERROR',
  BASE_FIND_ONE_ERROR = '#BASE_FIND_ONE_ERROR',
  BASE_FILTER_ERROR = '#BASE_FILTER_ERROR',
  BASE_UPDATE_ONE_ERROR = '#BASE_UPDATE_ONE_ERROR',
  BASE_UPDATE_MANY_ERROR = '#BASE_UPDATE_MANY_ERROR',
  BASE_UPDATE_ARRAY_ERROR = '#BASE_UPDATE_ARRAY_ERROR',
  BASE_UPDATE_ALL_ERROR = '#BASE_UPDATE_ALL_ERROR',
  BASE_DELETE_ONCE_ERROR = '#BASE_DELETE_ONCE_ERROR',
  BASE_DELETE_MANY_ERROR = '#BASE_DELETE_MANY_ERROR',
}
