version: '3.8'

services:
  chat-bot-demo:
    build: .
    image: chat-bot-demo:latest
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - MONGODB=${MONGODB}
      - OPENAI_API_KEY=${OPENAI_API_KEY}